Psimao pla 54
utilitywarehouse/data-infra-mono pull request #17
Opened 2022-07-25 19:18 UTC by paulosimao-ardanlabs

fixing name for bg-to-gcs

2022-07-26 10:05 UTC, AnthonyArdronUW requested changes
The .docs folder will also need to change to match the new format

2022-07-27 09:16 UTC, paulosimao-ardanlabs commented
> The .docs folder will also need to change to match the new format. https://github.com/utilitywarehouse/data-infra-mono/tree/psimao-pla-54/.doc

Fixed.

2022-07-28 13:58 UTC, catalin-ilea commented on .github/workflows/di-bq-to-gcs.yml
> +name: di-bq-to-gcs
should's this be di-bq-source to match the readme?

2022-07-28 14:05 UTC, paulosimao-ardanlabs commented on .github/workflows/di-bq-to-gcs.yml
> +name: di-bq-to-gcs
indeed it should.

2022-07-28 14:21 UTC, iainmillarUW approved these changes

2022-07-28 14:39 UTC, paulosimao-ardanlabs commented
> The .docs folder will also need to change to match the new format. https://github.com/utilitywarehouse/data-infra-mono/tree/psimao-pla-54/.doc

This has been addressed.

2022-07-28 14:43 UTC, catalin-ilea approved these changes

2022-07-28 14:43 UTC, AnthonyArdronUW approved these changes

2022-07-28 14:44 UTC, merged